### ISSUE TITLE
Drawer First time not working 

### ISSUE THREAD

**Issue by Ruchitdifferenz** [ssowri1/SPNavigationDrawerwithTABbar#2]
Hello 

After login screen when I come to drawer page and my tabbar selected index is 2  then drawer is not opened. I had also wrote code on TabbarController but it is not working please suggest me

Thanks 
Ruchit

**Comment by Ruchitdifferenz** [comment]
I had found the solution , when from any of Viewcontroller you go to the drawer at that time there must be navigate it , do not present view.

**Comment by ssowri1** [comment]
Oh. Than you so much for your response.
